export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  MONTH_LOCKED: 'MONTH_LOCKED',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',
  SETTLEMENT_ALREADY_LOCKED: 'SETTLEMENT_ALREADY_LOCKED',
  SETTLEMENT_PRECHECK_FAILED: 'SETTLEMENT_PRECHECK_FAILED',
  SETTLEMENT_WARNING_ACK_REQUIRED: 'SETTLEMENT_WARNING_ACK_REQUIRED',
  IMPORT_TEMPLATE_INVALID: 'IMPORT_TEMPLATE_INVALID',
  IMPORT_ROW_INVALID: 'IMPORT_ROW_INVALID',
  AUDIT_WRITE_FAILED: 'AUDIT_WRITE_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
