import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { RolesPage } from '../src/pages/RolesPage';
import { buildRolesQuery, canManageRoles, canReadRoles, containsSensitiveRoleField, nextModuleSelection, permissionGroups } from '../src/pages/role-utils';
const reader = { userId: 'u', roleCode: 'reader', permissions: ['role.read'] };
assert.equal(canReadRoles(reader), true); assert.equal(canManageRoles(reader), false);
assert.equal(buildRolesQuery({ page: 2, pageSize: 50, search: ' test ', status: 'active' }), 'page=2&pageSize=50&search=test&status=active');
assert.deepEqual(permissionGroups([{ module: 'role', id: '1' }, { module: 'admin', id: '2' }]).map(([name]) => name), ['admin', 'role']);
assert.deepEqual(nextModuleSelection(['1'], ['1', '2'], true).sort(), ['1', '2']); assert.deepEqual(nextModuleSelection(['1', '2', '3'], ['1', '2'], false), ['3']);
assert.equal(containsSensitiveRoleField({ tokenHash: 'secret' }), true); assert.equal(containsSensitiveRoleField({ items: [{ code: 'role.read' }] }), false);
const page = readFileSync(new URL('../src/pages/RolesPage.tsx', import.meta.url), 'utf8');
assert.equal(page.includes('modalApi.confirm'), true, 'disable requires confirmation'); assert.equal(page.includes('permissionIds'), true, 'final permission set must be submitted'); assert.equal(page.includes('模块全选/取消'), true); assert.equal(page.includes('disabled={r.system}'), true); assert.equal(page.includes('passwordHash'), false); assert.equal(page.includes('tokenHash'), false);
assert.equal(page.includes('afterOpenChange='), false, 'role editor animation must not reset entered values');
assert.equal(page.includes('if (!open) return;'), true, 'role editor must initialize after fields mount');
const managerMarkup = renderToStaticMarkup(createElement(RolesPage, { actor: { ...reader, permissions: ['role.read', 'role.manage'] } }));
const readerMarkup = renderToStaticMarkup(createElement(RolesPage, { actor: reader }));
assert.equal(managerMarkup.includes('角色与权限'), true, 'role page component must render');
assert.equal(managerMarkup.includes('创建角色'), true, 'manager interaction entry must render');
assert.equal(readerMarkup.includes('创建角色'), false, 'read-only component must hide write entry');
console.log('role-utils tests passed');
