-- Prisma's @default(uuid()) is generated by the client. Keep the database
-- definition aligned with the schema to avoid drift in fresh and existing DBs.
ALTER TABLE "sync_planning_runs" ALTER COLUMN "id" DROP DEFAULT;
